final_project/project/account_app/urls.py
from django.urls import path, include
from .views import HomeView, SignUp #UserListView, UserDetailView
from django.contrib.auth import views as auth_views 

urlpatterns = [
    path ('', HomeView.as_view(), name = 'homepage'),
    path('signup', SignUp.as_view(template_name = 'registration/signup.html'), name='signup'),
    path('login', auth_views.LoginView.as_view(template_name = 'registration/login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(next_page = 'homepage'), name = 'logout'),
    #path ('profile_list/', UserListView.as_view(template_name = 'registration/profile_list.html'), name= 'profile_list'),

]

final_project/project/menu_app/urls.py
# from project.account_app.views import HomeView
from django.urls import path
from . import views

urlpatterns = [

#path('', views.menu_list_view(template_name = 'menu_app/menu_list.html'), name = 'menu_list'),
path('menu/', views.menu_list_view, name = 'menu_list'),
#path ('', views.menu_category, name = 'menu_category'), 
path ('admin_page/', views.MenuItem, name = 'menu_item'),

]

final_project/project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account_app.urls')),
    path('', include('menu_app.urls')),
]

final_project/project/account_app/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User 
from django.conf import settings

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #orders = models.ManyToManyField(Order, blank=True)
    #addresses = models.ManyToManyField(Address)
    # items_ordered = models.ManyToManyField(OrderItem)
    def __str__(self):
        return f'{self.user.username}\'s Profile'

def post_save_profile_create(sender, instance, created, *args, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)
post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.TextField(max_length=400)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

final_project/project/menu_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class ToppingsCategory(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    description = models.TextField(max_length=100, blank=True, null=True, default='')

    def __str__(self):
        return self.name

class Topping(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits = 4, decimal_places=2, default=0)
    category = models.ForeignKey(ToppingsCategory, on_delete = models.PROTECT, default=None)
   
    def __str__(self):
        return self.name


class ItemsCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class MenuItem(models.Model):
    name = models.CharField(max_length=22)
    price = models.DecimalField(max_digits = 4, decimal_places=2)
    category = models.ForeignKey(ItemsCategory, on_delete = models.PROTECT)
    toppings = models.ManyToManyField(Topping, blank=True)
    #image = models.ImageField(default=None, upload_to='', null=True, blank=True)

    def __str__(self):
        return self.name


class OrderItem(models.Model):
    item = models.ForeignKey(MenuItem, on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits = 4, decimal_places=2, default=0)
    order_item_order = models.ForeignKey('menu_app.Order', on_delete=models.CASCADE, null=True)
   #toppings = models.ManyToManyField(Topping, blank=True)

    def __str__(self):
        return self.item.name

    def get_item_price(self):
        self.price = sum(topping.price for topping in self.toppings.all()) + self.item.price


    def get_all_topping_categories(self):
        categories = []
        for topping in self.toppings.all():
            if not topping.category in categories:
                categories.append(topping.category)
        return categories


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete = models.CASCADE)
    date_ordered = models.DateTimeField(default=timezone.now)
    items = models.ManyToManyField(MenuItem)
    order_items = models.ManyToManyField(OrderItem)
    total = models.DecimalField(max_digits = 6, decimal_places=2, null=True)
    is_ordered = models.BooleanField(default=False)
    pickup_time = models.DateTimeField(default=timezone.now)
    special_instructions = models.TextField(max_length=256, blank=True)

    def __str__(self):
        return f'Order #{self.id} - {self.customer.username}'

    # # url to redirect to when submitting order form
    # def get_absolute_url(self):
    #     return reverse('orders:order_detail', kwargs={'pk':self.pk})

    # returns the sum of each item price in order and assigns it to self.total
    def get_order_total(self):
        self.total = sum(order_item.price for order_item in self.order_items.all())

    def get_cart_items(self):
        return self.items.all()


    # class Meta():
    #     ordering = ['-date_ordered']

final_project/project/account_app/forms.py
from django.forms import ModelForm
from django import forms


from django.forms import ModelForm, widgets
from django.forms import Textarea
from .models import Contact
from django import forms 



class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)
       
# class ReviewsFrom(forms.Form):
#     name = forms.CharField(max_length= 100)
#     details = forms.CharField(widget=forms.Textarea)
#     date = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M"])

final_project/project/menu_app/forms.py
from django import forms 
from .models import CartItem, Cart

class AddToCartForm (forms.ModelForm): 
    cart = forms.ModelChoiceField(queryset = Cart.objects.filter(current = True), to_field_name = "user")
    class Meta: 
        model = CartItem
        fields = "__all__"

final_project/project/account_app/views.py
# Create your views here.
from django.shortcuts import redirect, render
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView, View
from django.contrib.auth.models import User
from .models import Profile 
from django.views.generic import ListView, DetailView

# Create your views here.

class SignUp(CreateView):
    form_class = UserCreationForm
    template_name = 'signup.html'
    context = {'from_class':form_class}
    success_url = reverse_lazy('login')   

    def form_valid (self, form_class):
        form_class.save()
        return super().form_valid(form_class)

class HomeView (TemplateView):
    template_name = "homepage.html"

class UserListView(ListView):
     model = Profile 

class UserDetailView (DetailView): 
    model= Profile 

final_project/project/menu_app/views.py
from .models import ( MenuItem,  ItemsCategory)
from django.views.generic import ListView
from django.shortcuts import render

class MenuListView(ListView):
    model = MenuItem
    template_name = 'items/menu_list.html'

def menu_list_view(request):
    item_list = MenuItem.objects.all()

    context = {'item_list': item_list,
                'item_categories':reversed(ItemsCategory.objects.all()),
                'item_categories_side_nav':reversed(ItemsCategory.objects.all())}

    return render(request, 'menu_app/menu_list.html', context)


def menu_item_detail(request, **kwargs):
    item = MenuItem.objects.filter(id=kwargs.get('pk')).first()

    context = {'item':item}

    return render(request, 'menu_app/item_details.html', context)

final_project/project/menu_app/templates/menu_app/admin.html
{% extends 'base.html' %}
<!-- {% load static %} -->
{% block content %}

{%for food in item %}
{{food.menu_category}}
{%endfor%}

<from >
    {%csrf_token%}
    {{form}}
    

</from>
{{food}}

{% endblock %}

final_project/project/menu_app/templates/menu_app/cart.html
{% extends 'base.html' %}

{% block content %}

    <div class = "container" >
        <div class = "container p-3">
            <h1> Your Shopping Cart </h1>
            <br>
            {%for item in cart_items %}
            <h4> {{item.add_item}}</h4>
            <p> quantity: {{item.quantity}}</p>
            <hr> 
            {%endfor%}
            <br>
            <form method="POST" action = "/placeorder/"> 
                {%csrf_token%}
                <input type = "submit" class = "btn btn-success" value="Place Order"> 
            
            </form>
            
        </div>

    </div>
{% endblock %}

final_project/project/menu_app/templates/menu_app/menu_list.html
{% extends 'base.html' %}
<!-- {% load static %} -->

{% block content %}





<link rel="stylesheet" type="text/css" href="{% static 'items/order_list.css' %}">


<style media="screen">
  body{
    margin-top:0;
  }
</style>

<!-- <div class="container">
  <h1 align='center'>Menu</h1>
  {% for item in menuitem_list %}
    <div class="jumbotron">
      <a href="{% url 'orders:item_detail' pk=item.id %}"><p>{{item.name}}</p></a>
      <p>{{item.price}}</p>
    </div>
  {% endfor %}
</div> -->

<header>
  <h1 style=>Our Menu</h1>
</header>

<section>
  <div class="order-list-content-section" ">

      <div class=>
        {% for category in item_categories %}
          <div id="{{category}}" >

              <h3 class="category-display" style="color:black;margin-bottom:25px;">{{category}}</h3>
            </div>

            <div class="row">
            {% for item in item_list %}
              {% if item.category == category %}
              
                  
                      <div class="price"></div>${{item.price}}</div>
                      <div class="item">
                          {{item}}
                      </div>
                    </div>
    
                  </button>
                </div>
              {% endif %}
            {% endfor %}
            </div>
          </div>
        {% endfor %}
      </div>

 
    </div>
 
</section>

{% endblock %}

final_project/project/menu_app/templates/menu_app/order_info.html
{% extends 'base.html' %}
<!-- {% load static %} -->

{% block content %}

<p> Test1 </p>
{% endblock %}